import asyncio
from sqlalchemy import text
from database import init_db, async_session_maker
from models import Package
from categorizer import categorize_package, generate_description

# Complete list of 1,759 packages
PACKAGE_NAMES = [
    "7zip", "a52dec", "aalib", "abseil-cpp", "accessibility-inspector",
    "accounts-qml-module", "accountsservice", "acl", "adwaita-cursors",
    "adwaita-fonts", "adwaita-icon-theme", "adwaita-icon-theme-legacy",
    "aha", "akonadi", "akonadi-calendar", "akonadi-calendar-tools",
    "akonadi-contacts", "akonadi-import-wizard", "akonadi-mime",
    "akonadi-search", "akonadiconsole", "akregator", "alligator",
    "alsa-card-profiles", "alsa-lib", "alsa-topology-conf",
    "alsa-ucm-conf", "alsa-utils", "analitza", "angelfish", "aom",
    "appstream", "appstream-qt", "aquamarine", "arch-install-scripts",
    "archlinux-appstream-data", "archlinux-keyring", "argon2", "arianna",
    "ark", "artikulate", "at-spi2-core", "atkmm", "attica", "attr",
    "audex", "audiocd-kio", "audiofile", "audiotube", "audit", "aurorae",
    "aurutils", "autoconf", "automake", "avahi", "avogadro-crystals",
    "avogadro-fragments", "avogadro-molecules", "avogadrolibs",
    "avogadrolibs-qt", "baloo", "baloo-widgets", "base", "base-devel",
    "bash", "bibata-cursor-theme-bin", "binutils", "bison",
    "black-hole-solver", "blas", "blinken", "bluedevil", "blueman",
    "bluez", "bluez-libs", "bluez-qt", "bluez-utils", "bolt", "bomber",
    "boost-libs", "bovo", "brave-bin", "breeze", "breeze-gtk",
    "breeze-icons", "breeze-plymouth", "brightnessctl", "brltty",
    "brotli", "bubblewrap", "bzip2", "c-ares", "ca-certificates",
    "ca-certificates-mozilla", "ca-certificates-utils", "cabextract",
    "cairo", "cairomm", "cairomm-1.16", "calendarsupport", "calligra",
    "cantarell-fonts", "cantor", "capstone", "catfish", "cauchy", "cava",
    "cblas", "cdparanoia", "cervisia", "cfitsio", "checkupdates-with-aur",
    "chromaprint", "cifs-utils", "clang", "claude-desktop-bin", "clinfo",
    "cliphist", "clucene", "cmake", "cmark", "colord", "colord-kde",
    "compiler-rt", "composefs", "containerd", "convertlit", "coordgen",
    "coreutils", "cppdap", "cpulimit", "cpulimit-debug", "cronie",
    "cryptsetup", "curl", "dav1d", "db5.3", "dbus", "dbus-broker",
    "dbus-broker-units", "dbus-units", "dconf", "ddcutil", "debugedit",
    "default-cursors", "desktop-file-utils", "device-mapper", "dhcpcd",
    "diffutils", "discord", "discount", "discover", "djvulibre", "dkms",
    "dmidecode", "docbook-xml", "docbook-xsl", "docker", "docker-desktop",
    "docker-desktop-debug", "dolphin", "dolphin-plugins", "dosfstools",
    "dotnet-host", "dotnet-runtime", "double-conversion", "dragon",
    "drawio-desktop", "drkonqi", "dtc", "duktape", "dunst", "e2fsprogs",
    "ebook-tools", "editorconfig-core-c", "edk2-aarch64", "edk2-arm",
    "edk2-ovmf", "efibootmgr", "efivar", "egl-gbm", "egl-wayland",
    "egl-x11", "eglexternalplatform", "electron", "electron37",
    "electron38", "elfutils", "elisa", "ell", "enchant", "eventviews",
    "exempi", "exfatprogs", "exiv2", "expat", "extra-cmake-modules",
    "eza", "faac", "faad2", "fakeroot", "falkon", "fastfetch", "ffmpeg",
    "ffmpeg4.4", "ffmpegthumbnailer", "ffmpegthumbs", "fftw", "figlet",
    "file", "filelight", "filesystem", "findutils", "firefox", "fish",
    "flac", "flatpak", "flatpak-kcm", "flex", "fluidsynth", "fmt",
    "fontconfig", "frameworkintegration", "francis", "freecell-solver",
    "freeglut", "freerdp", "freetype2", "frei0r-plugins", "fribidi",
    "fsearch-git", "fuse-common", "fuse2", "fuse3", "futuresql", "fzf",
    "gamemode", "gawk", "gc", "gcc", "gcc-libs", "gcr", "gcr-4", "gd",
    "gdb", "gdb-common", "gdbm", "gdk-pixbuf2", "gendesk",
    "geocode-glib-2", "geocode-glib-common", "gettext", "gfxstream",
    "ghostscript", "ghostty", "ghostty-shell-integration",
    "ghostty-terminfo", "ghostwriter", "giflib", "git", "glew",
    "glib-networking", "glib2", "glibc", "glibmm", "glibmm-2.68", "glm",
    "glslang", "glu", "glusterfs", "glycin", "gmp", "gn", "gnome-autoar",
    "gnome-calculator", "gnome-desktop", "gnome-desktop-4",
    "gnome-desktop-common", "gnome-keyring", "gnome-text-editor",
    "gnu-free-fonts", "gnugo", "gnulib-l10n", "gnupg", "gnutls",
    "gobject-introspection", "gobject-introspection-runtime",
    "gocryptfs", "google-chrome", "google-cloud-cli",
    "google-cloud-cli-bq", "google-cloud-cli-gsutil", "gperf",
    "gperftools", "gpgme", "gpgmepp", "gpick", "gpm", "gpsd",
    "granatier", "granite7", "grantlee", "grantlee-editor",
    "grantleetheme", "graphene", "graphite", "graphviz", "grep", "grim",
    "grimblast-git", "groff", "grub", "gsettings-desktop-schemas",
    "gsettings-system-schemas", "gsfonts", "gsl", "gsm", "gssdp",
    "gst-libav", "gst-plugin-pipewire", "gst-plugin-qml6",
    "gst-plugins-bad", "gst-plugins-bad-libs", "gst-plugins-base",
    "gst-plugins-base-libs", "gst-plugins-good", "gst-plugins-ugly",
    "gstreamer", "gtest", "gtk-layer-shell", "gtk-update-icon-cache",
    "gtk2", "gtk3", "gtk4", "gtk4-layer-shell", "gtkmm", "gtkmm-4.0",
    "gtkmm3", "gtksourceview5", "gts", "guile", "gum", "gupnp",
    "gupnp-dlna", "gupnp-igd", "gvfs", "gwenview", "gzip", "harfbuzz",
    "harfbuzz-icu", "hdf5", "hicolor-icon-theme", "hidapi", "highway",
    "htop", "http-parser", "hunspell", "hwdata", "hwloc", "hyphen",
    "hyprcursor", "hyprgraphics", "hypridle", "hyprland",
    "hyprland-qt-support", "hyprland-qtutils", "hyprlang", "hyprlock",
    "hyprpaper", "hyprpicker", "hyprshade", "hyprutils",
    "hyprwayland-scanner", "i2c-tools", "iana-etc", "icu", "id3lib",
    "ijs", "imagemagick", "imath", "imlib2", "imv", "incidenceeditor",
    "iniparser", "intel-gmmlib", "intel-media-driver", "intel-ucode",
    "iotop", "iproute2", "iptables", "iputils", "iso-codes",
    "isoimagewriter", "itinerary", "iwd", "jansson", "jasper",
    "java-environment-common", "java-runtime-common", "jbig2dec",
    "jbigkit", "jdk-openjdk", "jemalloc", "jq", "json-c", "json-glib",
    "jsoncpp", "juk", "k3b", "kaccounts-integration",
    "kaccounts-providers", "kactivitymanagerd", "kaddressbook",
    "kajongg", "kalarm", "kalgebra", "kalk", "kalm", "kalzium",
    "kamera", "kamoso", "kanagram", "kapman", "kapptemplate", "karchive",
    "karchive5", "kasts", "kate", "katomic", "kauth", "kauth5",
    "kbackup", "kbd", "kblackbox", "kblocks", "kbookmarks",
    "kbookmarks5", "kbounce", "kbreakout", "kbruch", "kcachegrind",
    "kcachegrind-common", "kcalc", "kcalendarcore", "kcalutils",
    "kcharselect", "kclock", "kcmutils", "kcodecs", "kcodecs5",
    "kcolorchooser", "kcolorpicker", "kcolorscheme", "kcompletion",
    "kcompletion5", "kconfig", "kconfig5", "kconfigwidgets",
    "kconfigwidgets5", "kcontacts", "kcoreaddons", "kcoreaddons5",
    "kcrash", "kcrash5", "kcron", "kdav", "kdbusaddons", "kdbusaddons5",
    "kde-cli-tools", "kde-dev-scripts", "kde-dev-utils",
    "kde-gtk-config", "kde-inotify-survey", "kdebugsettings",
    "kdeclarative", "kdeconnect", "kdecoration", "kded", "kded5",
    "kdeedu-data", "kdegraphics-mobipocket", "kdegraphics-thumbnailers",
    "kdenetwork-filesharing", "kdenlive", "kdepim-addons",
    "kdepim-runtime", "kdeplasma-addons", "kdesdk-kio",
    "kdesdk-thumbnailers", "kdesu", "kdesu5", "kdevelop",
    "kdevelop-php", "kdevelop-python", "kdf", "kdiagram", "kdialog",
    "kdiamond", "kdnssd", "kdoctools", "kdoctools5", "kdsoap-qt6",
    "kdsoap-ws-discovery-client", "keditbookmarks", "keysmith",
    "keyutils", "kfilemetadata", "kfind", "kfourinline", "kgamma",
    "kgeography", "kget", "kglobalaccel", "kglobalaccel5",
    "kglobalacceld", "kgoldrunner", "kgpg", "kgraphviewer",
    "kguiaddons", "kguiaddons5", "khangman", "khealthcertificate",
    "khelpcenter", "kholidays", "ki18n", "ki18n5", "kiconthemes",
    "kiconthemes5", "kidentitymanagement", "kidletime", "kig", "kigo",
    "killbots", "kimageannotator", "kimagemapeditor", "kimap",
    "kinfocenter", "kinit", "kio", "kio-admin", "kio-extras",
    "kio-fuse", "kio-gdrive", "kio-zeroconf", "kio5", "kirigami",
    "kirigami-addons", "kirigami-gallery", "kiriki", "kitemmodels",
    "kitemviews", "kitemviews5", "kiten", "kitinerary", "kitty",
    "kitty-shell-integration", "kitty-terminfo", "kjobwidgets",
    "kjobwidgets5", "kjournald", "kjumpingcube", "kldap", "kleopatra",
    "klettres", "klickety", "klines", "kmag", "kmahjongg", "kmail",
    "kmail-account-wizard", "kmailtransport", "kmbox", "kmenuedit",
    "kmime", "kmines", "kmix", "kmod", "kmousetool", "kmouth", "kmplot",
    "knavalbattle", "knetwalk", "knewstuff", "knights", "knotifications",
    "knotifications5", "knotifyconfig", "koko", "kolf", "kollision",
    "kolourpaint", "kompare", "kongress", "konqueror", "konquest",
    "konsole", "kontact", "kontactinterface", "kontrast",
    "konversation", "kopeninghours", "korganizer", "kosmindoormap",
    "kpackage", "kparts", "kparts5", "kpat", "kpeople", "kpimtextedit",
    "kpipewire", "kpkpass", "kplotting", "kpmcore", "kpty", "kpty5",
    "kpublictransport", "kqtquickcharts", "kquickcharts",
    "kquickimageeditor", "krb5", "krdc", "krdp", "krecorder", "kreversi",
    "krfb", "kruler", "krunner", "ksanecore", "kscreen",
    "kscreenlocker", "kservice", "kservice5", "kshisen", "ksirk",
    "ksmtp", "ksnakeduel", "kspaceduel", "ksquares", "ksshaskpass",
    "kstatusnotifieritem", "ksudoku", "ksvg", "ksystemlog",
    "ksystemstats", "kteatime", "ktextaddons", "ktexteditor",
    "ktexteditor5", "ktexttemplate", "ktextwidgets", "ktextwidgets5",
    "ktimer", "ktnef", "ktorrent", "ktouch", "ktrip", "ktuberling",
    "kturtle", "kubrick", "kunifiedpush", "kunitconversion",
    "kuserfeedback", "kwallet", "kwallet-pam", "kwallet5",
    "kwalletmanager", "kwave", "kwayland", "kweather", "kweathercore",
    "kwidgetsaddons", "kwidgetsaddons5", "kwin", "kwindowsystem",
    "kwindowsystem5", "kwordquiz", "kwrited", "kxmlgui", "kxmlgui5",
    "l-smash", "lame", "lapack", "layer-shell-qt", "lcms2", "ldb",
    "leancrypto", "leptonica", "less", "libabw", "libaccounts-glib",
    "libaccounts-qt", "libadwaita", "libaec", "libaemu", "libaio",
    "libakonadi", "libappindicator-gtk3", "libarchive", "libass",
    "libassuan", "libasyncns", "libatasmart", "libatomic_ops",
    "libavc1394", "libavif", "libavtp", "libb2", "libblockdev",
    "libblockdev-crypto", "libblockdev-fs", "libblockdev-loop",
    "libblockdev-mdraid", "libblockdev-nvme", "libblockdev-part",
    "libblockdev-swap", "libbluray", "libbpf", "libbs2b", "libbsd",
    "libburn", "libbytesize", "libcaca", "libcacard", "libcanberra",
    "libcap", "libcap-ng", "libcbor", "libcdio", "libcdio-paranoia",
    "libcdr", "libcloudproviders", "libcmis", "libcolord", "libcue",
    "libcups", "libdaemon", "libdatachannel", "libdatrie",
    "libdbusmenu-glib", "libdbusmenu-gtk3", "libdbusmenu-qt5",
    "libdc1394", "libdca", "libde265", "libdecor", "libdeflate",
    "libdisplay-info", "libdmtx", "libdovi", "libdrm", "libdv",
    "libdvdnav", "libdvdread", "libe-book", "libebur128", "libedit",
    "libei", "libelf", "libepoxy", "libepubgen", "libetonyek",
    "libevdev", "libevent", "libexif", "libexttextcat", "libfabric",
    "libfakekey", "libfdk-aac", "libffi", "libfontenc", "libfreeaptx",
    "libfreehand", "libfyaml", "libgcrypt", "libgee", "libgexiv2",
    "libgirepository", "libgit2", "libglvnd", "libgme", "libgnomekbd",
    "libgpg-error", "libgphoto2", "libgravatar", "libgsf", "libgudev",
    "libgusb", "libgweather-4", "libgxps", "libheif", "libical", "libice",
    "libidn", "libidn2", "libiec61883", "libieee1284", "libimagequant",
    "libimobiledevice", "libimobiledevice-glue", "libinih", "libinput",
    "libinstpatch", "libiptcdata", "libiscsi", "libisl", "libixion",
    "libjpeg-turbo", "libjuice", "libjxl", "libkcddb", "libkcompactdisc",
    "libkdcraw", "libkdegames", "libkdepim", "libkeduvocdocument",
    "libkexiv2", "libkgapi", "libkleo", "libkmahjongg", "libkolabxml",
    "libkomparediff2", "libksane", "libksba", "libkscreen", "libksieve",
    "libksysguard", "libktorrent", "liblangtag", "liblc3", "libldac",
    "libldap", "libliftoff", "liblouis", "liblqr", "liblrdf", "libltc",
    "libluv", "liblzf", "libmad", "libmalcontent", "libmanette",
    "libmaxminddb", "libmbim", "libmd", "libmfx", "libmicrodns",
    "libmm-glib", "libmng", "libmnl", "libmodplug", "libmpc",
    "libmpcdec", "libmpdclient", "libmpeg2", "libmspub", "libmsym",
    "libmtp", "libmusicbrainz5", "libmwaw", "libmysofa",
    "libnautilus-extension", "libndp", "libnet", "libnetfilter_conntrack",
    "libnewt", "libnfnetlink", "libnfs", "libnftnl", "libnghttp2",
    "libnghttp3", "libngtcp2", "libnice", "libnl", "libnm", "libnma",
    "libnma-common", "libnotify", "libnsl", "libnumbertext", "libnvme",
    "libodfgen", "libogg", "libolm", "libopenmpt", "liborcus",
    "libosinfo", "libp11-kit", "libpagemaker", "libpaper", "libpcap",
    "libpciaccess", "libpgm", "libphonenumber", "libpipewire",
    "libplacebo", "libplasma", "libplist", "libpng", "libportal",
    "libportal-gtk4", "libproxy", "libpsl", "libpulse",
    "libqaccessibilityclient-qt6", "libqalculate", "libqmi",
    "libqrtr-glib", "libquotient", "libqxp", "libraqm", "libraw",
    "libraw1394", "libreoffice-fresh", "libreoffice-fresh-en-gb",
    "librevenge", "librsvg", "librsync", "libsamplerate", "libsasl",
    "libseccomp", "libsecret", "libshout", "libsigc++", "libsigc++-3.0",
    "libsixel", "libslirp", "libsm", "libsndfile", "libsodium",
    "libsoup3", "libsoxr", "libspectre", "libspeechd", "libspelling",
    "libsrtp", "libssh", "libssh2", "libstaroffice", "libstemmer",
    "libsysprof-capture", "libtasn1", "libteam", "libthai", "libtheora",
    "libtiff", "libtirpc", "libtommath", "libtool", "libtpms",
    "libtraceevent", "libtracefs", "libunibreak", "libunistring",
    "libunwind", "liburcu", "liburing", "libusb", "libusbmuxd",
    "libutempter", "libutf8proc", "libuv", "libva", "libva-intel-driver",
    "libvdpau", "libverto", "libvisio", "libvlc", "libvncserver",
    "libvorbis", "libvpl", "libvpx", "libvterm", "libwacom",
    "libwbclient", "libwebp", "libwireplumber", "libwpd", "libwps",
    "libx11", "libxau", "libxaw", "libxcb", "libxcomposite", "libxcrypt",
    "libxcursor", "libxcvt", "libxdamage", "libxdmcp", "libxdp",
    "libxext", "libxfce4util", "libxfixes", "libxfont2", "libxft",
    "libxi", "libxinerama", "libxkbcommon", "libxkbcommon-x11",
    "libxkbfile", "libxklavier", "libxml2", "libxmlb", "libxmu",
    "libxnvctrl", "libxpm", "libxpresent", "libxrandr", "libxrender",
    "libxshmfence", "libxslt", "libxss", "libxt", "libxtst", "libxv",
    "libxvmc", "libxxf86vm", "libyaml", "libyuv", "libzip", "libzmf",
    "licenses", "lilv", "linux", "linux-api-headers", "linux-firmware",
    "linux-firmware-amdgpu", "linux-firmware-atheros",
    "linux-firmware-broadcom", "linux-firmware-cirrus",
    "linux-firmware-intel", "linux-firmware-mediatek",
    "linux-firmware-nvidia", "linux-firmware-other",
    "linux-firmware-radeon", "linux-firmware-realtek",
    "linux-firmware-whence", "lld", "llhttp", "llvm", "llvm-libs",
    "lm_sensors", "lmdb", "localsearch", "lokalize", "loupe", "lpsolve",
    "lskat", "lsof", "lua", "lua51-lpeg", "luajit", "lutris", "lv2",
    "lxappearance", "lz4", "lzo", "m4", "maeparser", "mailcap",
    "mailcommon", "mailimporter", "make", "man-pages", "marble",
    "marble-common", "mariadb", "mariadb-clients", "mariadb-libs",
    "markdownpart", "massif-visualizer", "mbedtls", "mbox-importer",
    "md4c", "mdadm", "media-player-info", "merkuro", "mesa",
    "mesa-utils", "meson", "messagelib", "milou", "mimetreeparser",
    "minizip", "minuet", "mjpegtools", "mkinitcpio", "mkinitcpio-busybox",
    "ml4w-hyprland", "mlt", "mobile-broadband-provider-info",
    "modemmanager", "modemmanager-qt", "mpdecimal", "mpfr", "mpg123",
    "mpv", "mpvqt", "msgpack-c", "mtdev", "mujs", "multipath-tools",
    "nano", "nautilus", "nautilus-open-any-terminal", "nautilus-python",
    "ncurses", "ndctl", "neochat", "neon", "neovim", "net-snmp",
    "net-tools", "netpbm", "nettle", "network-manager-applet",
    "networkmanager", "networkmanager-qt", "ninja", "nitrogen",
    "nm-connection-editor", "node-gyp", "nodejs", "nodejs-nopt",
    "noto-fonts", "noto-fonts-cjk", "noto-fonts-emoji",
    "noto-fonts-extra", "npm", "npth", "nspr", "nss", "ntfs-3g",
    "numactl", "nvidia-dkms", "nvidia-settings", "nvidia-utils", "nvm",
    "nwg-dock-hyprland", "nwg-look", "obs-studio", "obsidian",
    "ocean-sound-theme", "ocl-icd", "oh-my-posh-bin", "okular", "onetbb",
    "oniguruma", "onlyoffice-bin", "openal", "openbabel",
    "opencore-amr", "opencv", "openexr", "openh264", "openjpeg2",
    "openmpi", "openpmix", "openssh", "openssl", "opentimelineio",
    "openucx", "openxr", "opus", "orc", "os-prober", "osinfo-db",
    "ostree", "otf-font-awesome", "oxygen", "oxygen-sounds", "p11-kit",
    "pacman", "pacman-contrib", "pacman-mirrorlist", "pacseek",
    "pacutils", "palapeli", "pam", "pambase", "pamixer", "pango",
    "pangomm", "pangomm-2.48", "papirus-icon-theme", "parley", "parted",
    "partitionmanager", "paru", "paru-debug", "pass", "patch",
    "patchutils", "pavucontrol", "pciutils", "pcre", "pcre2", "pcsclite",
    "perl", "perl-common-sense", "perl-error", "perl-json-xs",
    "perl-mailtools", "perl-timedate", "perl-types-serialiser",
    "phonon-qt6", "phonon-qt6-mpv", "picmi", "pim-data-exporter",
    "pim-sieve-editor", "pimcommon", "pinentry", "pinta", "pipewire",
    "pipewire-alsa", "pipewire-audio", "pipewire-jack", "pipewire-pulse",
    "pixman", "pkgconf", "plasma-activities", "plasma-activities-stats",
    "plasma-browser-integration", "plasma-desktop", "plasma-disks",
    "plasma-firewall", "plasma-integration", "plasma-nm", "plasma-pa",
    "plasma-sdk", "plasma-systemmonitor", "plasma-thunderbolt",
    "plasma-vault", "plasma-welcome", "plasma-workspace",
    "plasma-workspace-wallpapers", "plasma5support", "plasmatube",
    "playerctl", "plymouth", "plymouth-kcm", "polkit", "polkit-gnome",
    "polkit-kde-agent", "polkit-qt5", "polkit-qt6", "poppler",
    "poppler-data", "poppler-glib", "poppler-qt6", "popt", "portaudio",
    "power-profiles-daemon", "powerdevil", "poxml", "ppp", "pps-tools",
    "print-manager", "prison", "procps-ng", "protobuf", "prrte",
    "psmisc", "pugixml", "pulseaudio-qt", "purpose", "pyside6", "python",
    "python-aaf2", "python-argcomplete", "python-attrs",
    "python-autocommand", "python-automat", "python-beautifulsoup4",
    "python-cairo", "python-certifi", "python-cffi",
    "python-charset-normalizer", "python-click", "python-constantly",
    "python-cryptography", "python-dbus", "python-distro",
    "python-evdev", "python-filelock", "python-gobject",
    "python-httplib2", "python-hyperlink", "python-idna",
    "python-imageio", "python-imageio-ffmpeg", "python-incremental",
    "python-jaraco.collections", "python-jaraco.context",
    "python-jaraco.functools", "python-jaraco.text", "python-lxml",
    "python-mako", "python-markdown", "python-markupsafe",
    "python-moddb", "python-more-itertools", "python-numpy",
    "python-packaging", "python-pexpect", "python-pillow", "python-pip",
    "python-pipx"python-platformdirs", "python-psutil", "python-ptyprocess",
    "python-pycparser", "python-pygdbmi", "python-pyparsing",
    "python-pywal", "python-pyxdg", "python-qtpy", "python-requests",
    "python-screeninfo", "python-sentry_sdk", "python-setuptools",
    "python-six", "python-soupsieve", "python-tqdm", "python-twisted",
    "python-typing_extensions", "python-urllib3", "python-userpath",
    "python-wheel", "python-yaml", "python-ytmusicapi",
    "python-zope-interface", "python310", "qca-qt5", "qca-qt6", "qcoro",
    "qemu-audio-alsa", "qemu-audio-dbus", "qemu-audio-jack",
    "qemu-audio-oss", "qemu-audio-pa", "qemu-audio-pipewire",
    "qemu-audio-sdl", "qemu-audio-spice", "qemu-base",
    "qemu-block-curl", "qemu-block-dmg", "qemu-block-gluster",
    "qemu-block-iscsi", "qemu-block-nfs", "qemu-block-ssh",
    "qemu-chardev-baum", "qemu-chardev-spice", "qemu-common",
    "qemu-desktop", "qemu-docs", "qemu-emulators-full", "qemu-full",
    "qemu-hw-display-qxl", "qemu-hw-display-virtio-gpu",
    "qemu-hw-display-virtio-gpu-gl", "qemu-hw-display-virtio-gpu-pci",
    "qemu-hw-display-virtio-gpu-pci-gl",
    "qemu-hw-display-virtio-gpu-pci-rutabaga",
    "qemu-hw-display-virtio-gpu-rutabaga",
    "qemu-hw-display-virtio-vga", "qemu-hw-display-virtio-vga-gl",
    "qemu-hw-display-virtio-vga-rutabaga",
    "qemu-hw-s390x-virtio-gpu-ccw", "qemu-hw-uefi-vars",
    "qemu-hw-usb-host", "qemu-hw-usb-redirect", "qemu-hw-usb-smartcard",
    "qemu-img", "qemu-pr-helper", "qemu-system-aarch64",
    "qemu-system-alpha", "qemu-system-alpha-firmware",
    "qemu-system-arm", "qemu-system-arm-firmware", "qemu-system-avr",
    "qemu-system-hppa", "qemu-system-hppa-firmware",
    "qemu-system-loongarch64", "qemu-system-m68k",
    "qemu-system-microblaze", "qemu-system-microblaze-firmware",
    "qemu-system-mips", "qemu-system-or1k", "qemu-system-ppc",
    "qemu-system-ppc-firmware", "qemu-system-riscv",
    "qemu-system-riscv-firmware", "qemu-system-rx", "qemu-system-s390x",
    "qemu-system-s390x-firmware", "qemu-system-sh4",
    "qemu-system-sparc", "qemu-system-sparc-firmware",
    "qemu-system-tricore", "qemu-system-x86", "qemu-system-x86-firmware",
    "qemu-system-xtensa", "qemu-tests", "qemu-tools", "qemu-ui-curses",
    "qemu-ui-dbus", "qemu-ui-egl-headless", "qemu-ui-gtk",
    "qemu-ui-opengl", "qemu-ui-sdl", "qemu-ui-spice-app",
    "qemu-ui-spice-core", "qemu-user", "qemu-vhost-user-gpu",
    "qemu-vmsr-helper", "qgpgme", "qhull", "qqc2-breeze-style",
    "qqc2-desktop-style", "qrca", "qrencode", "qt5-base",
    "qt5-declarative", "qt5-multimedia", "qt5-quickcontrols",
    "qt5-script", "qt5-speech", "qt5-svg", "qt5-translations",
    "qt5-wayland", "qt5-x11extras", "qt5-xmlpatterns", "qt5ct",
    "qt6-5compat", "qt6-base", "qt6-charts", "qt6-connectivity",
    "qt6-declarative", "qt6-httpserver", "qt6-imageformats",
    "qt6-location", "qt6-multimedia", "qt6-multimedia-ffmpeg",
    "qt6-multimedia-gstreamer", "qt6-networkauth", "qt6-positioning",
    "qt6-quick3d", "qt6-quicktimeline", "qt6-scxml", "qt6-sensors",
    "qt6-shadertools", "qt6-speech", "qt6-svg", "qt6-tools",
    "qt6-translations", "qt6-virtualkeyboard", "qt6-wayland",
    "qt6-webchannel", "qt6-webengine", "qt6-websockets", "qt6-webview",
    "qt6ct", "qtkeychain-qt6", "raptor", "rasqal", "rav1e", "rdma-core",
    "re2", "readline", "recastnavigation", "redland", "rhash", "ripgrep",
    "ripgrep-all", "rnnoise", "rocs", "rofi", "rpcbind", "rsync",
    "rtkit", "rtmpdump", "rubberband", "run-parts", "runc", "rust",
    "rutabaga-ffi", "samba", "sane", "sbc", "sdbus-cpp", "sddm",
    "sddm-kcm", "sdl12-compat", "sdl2-compat", "sdl2_image", "sdl2_ttf",
    "sdl3", "seabios", "seatd", "sed", "semver", "serd", "shaderc",
    "shadow", "shared-mime-info", "shiboken6",
    "signon-kwallet-extension", "signon-plugin-oauth2", "signon-ui",
    "signond", "simdjson", "skanlite", "skanpage", "skladnik", "slang",
    "slurp", "smartmontools", "smbclient", "snappy", "sndio", "socat",
    "sof-firmware", "solid", "solid5", "sonnet", "sonnet5", "sord",
    "sound-theme-freedesktop", "soundtouch", "source-highlight",
    "spandsp", "spdlog", "spectacle", "speex", "speexdsp", "spglib",
    "spice", "spice-protocol", "spirv-tools", "sqlite", "sratom", "srt",
    "starship", "startup-notification", "step", "stow", "sudo",
    "svgpart", "svt-av1", "svt-hevc", "swaync", "sweeper", "syndication",
    "syntax-highlighting", "syntax-highlighting5", "systemd",
    "systemd-libs", "systemd-sysvcompat", "systemsettings", "taglib",
    "talloc", "tar", "tcl", "tdb", "telly-skout", "tesseract",
    "tesseract-data-afr", "tesseract-data-osd", "tevent", "texinfo",
    "threadweaver", "timeshift", "tinysparql", "tk", "tmux", "tokodon",
    "tomlplusplus", "totem-pl-parser", "tpm2-tss", "tree", "tree-sitter",
    "tree-sitter-c", "tree-sitter-lua", "tree-sitter-markdown",
    "tree-sitter-query", "tree-sitter-vim", "tree-sitter-vimdoc", "tslib",
    "ttf-carlito", "ttf-dejavu", "ttf-fira-code", "ttf-fira-sans",
    "ttf-firacode-nerd", "ttf-hack", "ttf-jetbrains-mono",
    "ttf-liberation", "tumbler", "twolame", "tzdata", "uchardet",
    "udisks2", "umbrello", "unibilium", "unzip", "upower",
    "usb_modeswitch", "usbredir", "usbutils", "uthash", "util-linux",
    "util-linux-libs", "uwsm", "v4l-utils", "vapoursynth", "vde2",
    "verdict", "vid.stab", "vim", "vim-runtime", "virglrenderer",
    "virtiofsd", "virtualbox", "virtualbox-host-modules-arch",
    "visual-studio-code-bin", "vlc-plugin-a52dec", "vlc-plugin-alsa",
    "vlc-plugin-archive", "vlc-plugin-dav1d", "vlc-plugin-dbus",
    "vlc-plugin-dbus-screensaver", "vlc-plugin-faad2",
    "vlc-plugin-ffmpeg", "vlc-plugin-flac", "vlc-plugin-gnutls",
    "vlc-plugin-inflate", "vlc-plugin-journal", "vlc-plugin-jpeg",
    "vlc-plugin-mpg123", "vlc-plugin-ogg", "vlc-plugin-opus",
    "vlc-plugin-png", "vlc-plugin-shout", "vlc-plugin-speex",
    "vlc-plugin-tag", "vlc-plugin-theora", "vlc-plugin-twolame",
    "vlc-plugin-vorbis", "vlc-plugin-vpx", "vlc-plugin-xml",
    "vlc-plugins-base", "vlc-plugins-video-output", "vmaf", "volume_key",
    "vte-common", "vte3", "vtk", "vulkan-icd-loader", "vulkan-intel",
    "vulkan-mesa-device-select", "vulkan-tools", "w3m", "wacomtablet",
    "wavpack", "waybar", "wayland", "wayland-docs", "wayland-protocols",
    "wayland-utils", "waypaper", "webkit2gtk-4.1", "webp-pixbuf-loader",
    "webrtc-audio-processing-1", "wget", "which", "wildmidi", "wine",
    "wireless_tools", "wireplumber", "wl-clipboard", "wlogout",
    "wlr-randr", "woff2", "woff2-font-awesome", "wofi", "wolfssl",
    "wpa_supplicant", "x264", "x265", "xapian-core", "xapp",
    "xcb-imdkit", "xcb-proto", "xcb-util", "xcb-util-cursor",
    "xcb-util-errors", "xcb-util-image", "xcb-util-keysyms",
    "xcb-util-renderutil", "xcb-util-wm", "xclip", "xcur2png",
    "xdg-dbus-proxy", "xdg-desktop-portal", "xdg-desktop-portal-gtk",
    "xdg-desktop-portal-hyprland", "xdg-desktop-portal-kde",
    "xdg-user-dirs", "xdg-user-dirs-gtk", "xdg-utils", "xerces-c",
    "xf86-input-libinput", "xf86-input-wacom", "xf86-video-intel",
    "xfconf", "xkeyboard-config", "xmlsec", "xorg-fonts-encodings",
    "xorg-server", "xorg-server-common", "xorg-setxkbmap", "xorg-xauth",
    "xorg-xdpyinfo", "xorg-xev", "xorg-xinit", "xorg-xkbcomp",
    "xorg-xmessage", "xorg-xmodmap", "xorg-xprop", "xorg-xrandr",
    "xorg-xrdb", "xorg-xset", "xorg-xsetroot", "xorg-xwayland",
    "xorgproto", "xsettingsd", "xvidcore", "xxhash", "xz", "yakuake",
    "yarn", "yay", "yay-debug", "yt-dlp", "yyjson", "zanshin", "zbar",
    "zeromq", "zimg", "zip", "zix", "zlib", "zlib-ng", "zram-generator",
    "zsh", "zsh-completions", "zstd", "zvbi", "zxing-cpp"
]

async def seed_database():
    """Seed the database with all 1,759 packages."""
    print("🔧 Initializing database schema...")
    await init_db()
    
    print("📦 Starting package seeding process...")
    async with async_session_maker() as session:
        # Check if database is already seeded
        result = await session.execute(text("SELECT COUNT(*) FROM packages"))
        count = result.scalar()
        
        if count > 0:
            print(f"✅ Database already contains {count} packages. Skipping seed.")
            return
        
        print(f"📊 Categorizing and inserting {len(PACKAGE_NAMES)} packages...")
        
        # Process packages in batches for better performance
        batch_size = 100
        for i in range(0, len(PACKAGE_NAMES), batch_size):
            batch = PACKAGE_NAMES[i:i + batch_size]
            
            for idx, package_name in enumerate(batch, start=i+1):
                category = categorize_package(package_name)
                description = generate_description(package_name, category)
                
                package = Package(
                    id=idx,
                    name=package_name,
                    category=category,
                    description=description
                )
                session.add(package)
            
            await session.flush()
            print(f"   Processed {min(i + batch_size, len(PACKAGE_NAMES))}/{len(PACKAGE_NAMES)} packages...")
        
        # Create full-text search vectors
        print("🔍 Creating full-text search indexes...")
        await session.execute(text("""
            UPDATE packages 
            SET search_vector = to_tsvector('english', name || ' ' || description)
        """))
        
        await session.commit()
        print(f"✨ Successfully seeded {len(PACKAGE_NAMES)} packages!")
        print("🎉 Database is ready!")

if __name__ == "__main__":
    asyncio.run(seed_database())